server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Hỗ trợ React Router (client-side routing) quay về index.html nếu không tìm thấy file tĩnh
        try_files $uri $uri/ /index.html;
    }

    # Báo lỗi 50x nếu có sự cố máy chủ
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
